export const REVIEW_KEYMAP = {
  nextFile: "j",
  prevFile: "k",
  nextHunk: "n",
  prevHunk: "p",
  approve: "a",
  reject: "r",
  note: "m",
  save: "s",
  quit: "q",
  nextTab: "l",
  prevTab: "h",
  filter: "f",
  approveAll: "A",
  rejectAll: "R",
} as const;
